{
 "title": "Carbon Aware KEDA",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Carbon Intensity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "carbon_aware_keda_scaler_carbon_intensity{namespace=\"carbon-aware-keda-operator-system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciles",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "carbon_aware_keda_scaler_reconciles_total{app=\"word-processor-carbon-aware-keda-scaler\"}",
     "legendFormat": "Reconcile Count"
    },
    {
     "expr": "carbon_aware_keda_scaler_reconcile_errors_total{app=\"word-processor-carbon-aware-keda-scaler\"}",
     "legendFormat": "Error Count"
    }
   ]
  },
  {
   "title": "Reconciles, EcoModeOff, Error",
   "type": "timeseries",
   "description": "Counters for number of reconciles, errors, and eco mode off states",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "carbon_aware_keda_scaler_eco_mode_off{code=\"1\"}",
     "legendFormat": "EcoModeOff Total"
    },
    {
     "expr": "carbon_aware_keda_scaler_reconciles_total",
     "legendFormat": "Reconcile Total"
    },
    {
     "expr": "carbon_aware_keda_scaler_reconcile_errors_total",
     "legendFormat": "Error Total"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "carbon_aware_keda_scaler_max_replicas{app=\"word-processor-carbon-aware-keda-scaler\"}",
     "legendFormat": "Carbon Aware Max Replicas"
    },
    {
     "expr": "carbon_aware_keda_scaler_default_max_replicas{app=\"word-processor-carbon-aware-keda-scaler\"}",
     "legendFormat": "Default Max Replicas"
    }
   ]
  }
 ]
}