apiVersion: carbonaware.kubernetes.azure.com/v1alpha1
kind: CarbonAwareKedaScaler
metadata:
  labels:
    app.kubernetes.io/name: carbonawarekedascaler
    app.kubernetes.io/instance: carbonawarekedascaler-sample
    app.kubernetes.io/part-of: carbon-aware-keda-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: carbon-aware-keda-operator
  name: carbonawarekedascaler-sample
spec:
  kedaTarget: scaledobjects.keda.sh
  kedaTargetRef:
    name: mynginx-scaledobject
    namespace: default
  carbonIntensityForecastDataSource:       # carbon intensity forecast data source
    mockCarbonForecast: true               # [OPTIONAL] use mock carbon forecast data 
    localConfigMap:                        # [OPTIONAL] use configmap for carbon forecast data 
      name: carbon-intensity 
      namespace: kube-system
      key: data 
  maxReplicasByCarbonIntensity:            # array of carbon intensity values in ascending order; each threshold value represents the upper limit and previous entry represents lower limit
    - carbonIntensityThreshold: 566        # when carbon intensity is 566 or below
      maxReplicas: 110                     # do more
    - carbonIntensityThreshold: 633         # when carbon intensity is >566 and <=633
      maxReplicas: 60
    - carbonIntensityThreshold: 700        # when carbon intensity is >633 and <=700 (or above)
      maxReplicas: 10                      # do less
  ecoModeOff:                              # [OPTIONAL] settings to override carbon awareness; can override based on high intensity duration or schedules
    maxReplicas: 100                       # when carbon awareness is disabled, use this value
    carbonIntensityDuration:               # [OPTIONAL] disable carbon awareness when carbon intensity is high for this length of time
      carbonIntensityThreshold: 688        # when carbon intensity is equal to or above this value, consider it high
      overrideEcoAfterDurationInMins: 60   # if carbon intensity is high for this many hours disable ecomode
    customSchedule:                        # [OPTIONAL] disable carbon awareness during specified time periods
      - startTime: "2023-03-14T22:00:00Z"  # start time in UTC
        endTime: "2023-03-14T23:59:59Z"    # end time in UTC
    recurringSchedule:                     # [OPTIONAL] disable carbon awareness during specified recurring time periods
      - "* 22-23 * * 1-5"                  # cron syntax for every weekday from 10pm to 12am also in UTC
      - "* 00-01 * * 1-5"                  # cron syntax cannot span across days so this is 12am to 2am