//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarbonAwareKedaScaler) DeepCopyInto(out *CarbonAwareKedaScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonAwareKedaScaler.
func (in *CarbonAwareKedaScaler) DeepCopy() *CarbonAwareKedaScaler {
	if in == nil {
		return nil
	}
	out := new(CarbonAwareKedaScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CarbonAwareKedaScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarbonAwareKedaScalerList) DeepCopyInto(out *CarbonAwareKedaScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CarbonAwareKedaScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonAwareKedaScalerList.
func (in *CarbonAwareKedaScalerList) DeepCopy() *CarbonAwareKedaScalerList {
	if in == nil {
		return nil
	}
	out := new(CarbonAwareKedaScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CarbonAwareKedaScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarbonAwareKedaScalerSpec) DeepCopyInto(out *CarbonAwareKedaScalerSpec) {
	*out = *in
	out.KedaTargetRef = in.KedaTargetRef
	if in.MaxReplicasByCarbonIntensity != nil {
		in, out := &in.MaxReplicasByCarbonIntensity, &out.MaxReplicasByCarbonIntensity
		*out = make([]CarbonIntensityConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.EcoModeOff.DeepCopyInto(&out.EcoModeOff)
	out.CarbonIntensityForecastDataSource = in.CarbonIntensityForecastDataSource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonAwareKedaScalerSpec.
func (in *CarbonAwareKedaScalerSpec) DeepCopy() *CarbonAwareKedaScalerSpec {
	if in == nil {
		return nil
	}
	out := new(CarbonAwareKedaScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarbonAwareKedaScalerStatus) DeepCopyInto(out *CarbonAwareKedaScalerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonAwareKedaScalerStatus.
func (in *CarbonAwareKedaScalerStatus) DeepCopy() *CarbonAwareKedaScalerStatus {
	if in == nil {
		return nil
	}
	out := new(CarbonAwareKedaScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarbonIntensityConfig) DeepCopyInto(out *CarbonIntensityConfig) {
	*out = *in
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonIntensityConfig.
func (in *CarbonIntensityConfig) DeepCopy() *CarbonIntensityConfig {
	if in == nil {
		return nil
	}
	out := new(CarbonIntensityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarbonIntensityDuration) DeepCopyInto(out *CarbonIntensityDuration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonIntensityDuration.
func (in *CarbonIntensityDuration) DeepCopy() *CarbonIntensityDuration {
	if in == nil {
		return nil
	}
	out := new(CarbonIntensityDuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarbonIntensityForecastDataSource) DeepCopyInto(out *CarbonIntensityForecastDataSource) {
	*out = *in
	out.LocalConfigMap = in.LocalConfigMap
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonIntensityForecastDataSource.
func (in *CarbonIntensityForecastDataSource) DeepCopy() *CarbonIntensityForecastDataSource {
	if in == nil {
		return nil
	}
	out := new(CarbonIntensityForecastDataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EcoModeOff) DeepCopyInto(out *EcoModeOff) {
	*out = *in
	out.CarbonIntensityDuration = in.CarbonIntensityDuration
	if in.CustomSchedule != nil {
		in, out := &in.CustomSchedule, &out.CustomSchedule
		*out = make([]Schedule, len(*in))
		copy(*out, *in)
	}
	if in.RecurringSchedule != nil {
		in, out := &in.RecurringSchedule, &out.RecurringSchedule
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EcoModeOff.
func (in *EcoModeOff) DeepCopy() *EcoModeOff {
	if in == nil {
		return nil
	}
	out := new(EcoModeOff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KedaTargetRef) DeepCopyInto(out *KedaTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KedaTargetRef.
func (in *KedaTargetRef) DeepCopy() *KedaTargetRef {
	if in == nil {
		return nil
	}
	out := new(KedaTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalConfigMap) DeepCopyInto(out *LocalConfigMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalConfigMap.
func (in *LocalConfigMap) DeepCopy() *LocalConfigMap {
	if in == nil {
		return nil
	}
	out := new(LocalConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Schedule) DeepCopyInto(out *Schedule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schedule.
func (in *Schedule) DeepCopy() *Schedule {
	if in == nil {
		return nil
	}
	out := new(Schedule)
	in.DeepCopyInto(out)
	return out
}
