name: Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set lower case repo name
      run: |
        echo "REPOSITORY_NAME_LOWER=${REPOSITORY_NAME,,}" >>${GITHUB_ENV}
      env:
        REPOSITORY_NAME: '${{ github.repository }}'
    - name: Login GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Build and push the container image
      run: |
        make docker-buildx IMG=ghcr.io/${{ env.REPOSITORY_NAME_LOWER }}:${{ github.ref_name }} PLATFORMS=linux/amd64,linux/arm64
    - name: Build deployment YAML file
      run: |
        cd config/manager && kustomize edit set image controller=ghcr.io/${{ env.REPOSITORY_NAME_LOWER }}:${{ github.ref_name }}
        cd -
        kustomize build config/default > carbonawarekedascaler-${{ github.ref_name }}.yaml
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Upload deployment YAML file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./carbonawarekedascaler-${{ github.ref_name }}.yaml
        asset_name: carbonawarekedascaler-${{ github.ref_name }}.yaml
        asset_content_type: application/x-yaml